### PR TITLE
Initial project structure

### PR DESCRIPTION
**Pull request by Codestech1**
Adds an initial gradle project and packet structure.

### CODE REVIEW

**Review by JSDforJ — DISMISSED** [review]

**Comment by Codestech1** [comment]
Modifying this pull request to create a non-breaking API via interfaces

**Comment by Codestech1** [comment]
Serializing NBT text components is not possible for now, because kyori has not a serializer for them *yet*.
https://github.com/KyoriPowered/adventure/issues/995

**Comment by JSDforJ** [comment]
We should create an event system and integrate it with the packet system before merging, ie. the Packet class should extend Event.

Small thing:
if fx. B Event extends A event, then when B is called it should also call A event

**Comment by JSDforJ** [comment]
ie calling an event should also call its parents

**Comment by Codestech1** [comment]
> We should create an event system and integrate it with the packet system before merging, ie. the Packet class should extend Event.
> 
> Small thing: if fx. B Event extends A event, then when B is called it should also call A event

The goal for now was achieving a working connection between server and client and a basic packet system.
Wouldn't it be better to make an event system in another PR?

**Comment by JSDforJ** [comment]
well fx. the requeststatus packet will call an event, which will send an respondstatus packet instead of it comming directly from the other packet

**Comment by Codestech1** [comment]
> well fx. the requeststatus packet will call an event, which will send an respondstatus packet instead of it comming directly from the other packet

I could start making an event system now, but in another PR.

**Review by JSDforJ — APPROVED** [review]

**Pull request merged**
